import 'package:strengthwise/models/exercise/exercise.dart';
import 'package:strengthwise/models/tracking_mode.dart';

/// 測試用動作工廠
///
/// 提供 [makeTestExercise] 建立自訂動作，
/// 以及 [standardTestExercises] 標準 12 筆測試資料集，
/// 涵蓋 v5.0 所有分類維度。
class ExerciseTestFactory {
  /// 建立測試用 Exercise，所有必填欄位有合理預設值
  ///
  /// 可覆蓋任何欄位（含 v5.0 分類欄位）。
  static Exercise make({
    String id = 'test-id',
    String name = '測試動作',
    String nameEn = 'Test Exercise',
    List<String> bodyParts = const ['胸'],
    String type = '重訓',
    String equipment = 'barbell',
    String jointType = 'compound',
    String level1 = '重訓',
    String level2 = '胸',
    String level3 = '',
    String level4 = '',
    String level5 = '',
    String trainingType = '重訓',
    String bodyPart = '胸',
    String specificMuscle = '',
    String equipmentCategory = '自由重量',
    String equipmentSubcategory = '槓鈴',
    String trainingTypeEn = 'Resistance',
    String bodyPartEn = 'Chest',
    String specificMuscleEn = '',
    String equipmentCategoryEn = 'Free Weight',
    String equipmentSubcategoryEn = 'Barbell',
    String? actionName,
    String description = '',
    String imageUrl = '',
    String videoUrl = '',
    List<String> apps = const ['strengthwise'],
    DateTime? createdAt,
    TrackingMode trackingMode = TrackingMode.weightReps,
    // v5.0+
    String? canonicalName,
    String? canonicalNameEn,
    List<String> movementPatterns = const [],
    List<String> pplTags = const [],
    String? primaryMuscle,
    List<String> synergistMuscles = const [],
    String mechanicsType = 'compound',
    bool isUnilateral = false,
    String difficultyLevel = 'beginner',
    bool isExplosive = false,
    List<String> aliases = const [],
  }) {
    return Exercise(
      id: id,
      name: name,
      nameEn: nameEn,
      bodyParts: bodyParts,
      type: type,
      equipment: equipment,
      jointType: jointType,
      level1: level1,
      level2: level2,
      level3: level3,
      level4: level4,
      level5: level5,
      trainingType: trainingType,
      bodyPart: bodyPart,
      specificMuscle: specificMuscle,
      equipmentCategory: equipmentCategory,
      equipmentSubcategory: equipmentSubcategory,
      trainingTypeEn: trainingTypeEn,
      bodyPartEn: bodyPartEn,
      specificMuscleEn: specificMuscleEn,
      equipmentCategoryEn: equipmentCategoryEn,
      equipmentSubcategoryEn: equipmentSubcategoryEn,
      actionName: actionName,
      description: description,
      imageUrl: imageUrl,
      videoUrl: videoUrl,
      apps: apps,
      createdAt: createdAt ?? DateTime(2026, 1, 1),
      trackingMode: trackingMode,
      canonicalName: canonicalName,
      canonicalNameEn: canonicalNameEn,
      movementPatterns: movementPatterns,
      pplTags: pplTags,
      primaryMuscle: primaryMuscle,
      synergistMuscles: synergistMuscles,
      mechanicsType: mechanicsType,
      isUnilateral: isUnilateral,
      difficultyLevel: difficultyLevel,
      isExplosive: isExplosive,
      aliases: aliases,
    );
  }

  /// 標準 12 筆測試資料集
  ///
  /// 涵蓋維度：
  /// - 動作模式：9/22（horizontal_push, squat, hinge, vertical_pull,
  ///   anti_extension, lunge, isolation_push, horizontal_pull, mobility）
  /// - PPL 標籤：6/6（push, pull, legs, core, mobility, cardio）
  /// - 器材：5/19（barbell, dumbbell, bodyweight, cable, kettlebell）
  /// - 肌肉群：7/26（pec_major_sternal, quads, hamstrings, lats, abs, triceps, glutes）
  /// - 特殊：is_explosive=true(2), isolation(2), compound(10)
  /// - 難度：beginner(5), intermediate(4), advanced(3)
  static List<Exercise> get standardDataset => [
    // ex-001: 槓鈴臥推（horizontal_push, push, barbell, intermediate）
    make(
      id: 'ex-001',
      name: '槓鈴臥推',
      nameEn: 'Barbell Bench Press',
      canonicalName: '平板槓鈴臥推',
      canonicalNameEn: 'Flat Barbell Bench Press',
      movementPatterns: ['horizontal_push'],
      pplTags: ['push'],
      primaryMuscle: 'pec_major_sternal',
      synergistMuscles: ['anterior_deltoid', 'triceps'],
      equipment: 'barbell',
      mechanicsType: 'compound',
      difficultyLevel: 'intermediate',
      isExplosive: false,
      trackingMode: TrackingMode.weightReps,
      aliases: ['仰臥推舉', 'BP', 'Bench Press'],
      level1: '重訓',
      level2: '胸',
      bodyParts: ['胸'],
      bodyPart: '胸',
    ),

    // ex-002: 啞鈴臥推（horizontal_push, push, dumbbell, beginner）
    make(
      id: 'ex-002',
      name: '啞鈴臥推',
      nameEn: 'Dumbbell Bench Press',
      canonicalName: '平板啞鈴臥推',
      canonicalNameEn: 'Flat Dumbbell Bench Press',
      movementPatterns: ['horizontal_push'],
      pplTags: ['push'],
      primaryMuscle: 'pec_major_sternal',
      synergistMuscles: ['anterior_deltoid', 'triceps'],
      equipment: 'dumbbell',
      mechanicsType: 'compound',
      difficultyLevel: 'beginner',
      isExplosive: false,
      trackingMode: TrackingMode.weightReps,
      aliases: ['啞鈴推胸', 'DB Bench'],
      level1: '重訓',
      level2: '胸',
      bodyParts: ['胸'],
      bodyPart: '胸',
    ),

    // ex-003: 槓鈴深蹲（squat, legs, barbell, intermediate）
    make(
      id: 'ex-003',
      name: '槓鈴深蹲',
      nameEn: 'Barbell Back Squat',
      canonicalName: '槓鈴背蹲',
      canonicalNameEn: 'Barbell Back Squat',
      movementPatterns: ['squat'],
      pplTags: ['legs'],
      primaryMuscle: 'quads',
      synergistMuscles: ['glutes', 'hamstrings'],
      equipment: 'barbell',
      mechanicsType: 'compound',
      difficultyLevel: 'intermediate',
      isExplosive: false,
      trackingMode: TrackingMode.weightReps,
      aliases: ['自由深蹲', 'Back Squat'],
      level1: '重訓',
      level2: '腿',
      bodyParts: ['腿'],
      bodyPart: '腿',
    ),

    // ex-004: 傳統硬舉（hinge, pull+legs, barbell, advanced）— 雙 PPL
    make(
      id: 'ex-004',
      name: '傳統硬舉',
      nameEn: 'Conventional Deadlift',
      canonicalName: '槓鈴傳統硬舉',
      canonicalNameEn: 'Barbell Conventional Deadlift',
      movementPatterns: ['hinge'],
      pplTags: ['pull', 'legs'],
      primaryMuscle: 'hamstrings',
      synergistMuscles: ['glutes', 'erector_spinae'],
      equipment: 'barbell',
      mechanicsType: 'compound',
      difficultyLevel: 'advanced',
      isExplosive: false,
      trackingMode: TrackingMode.weightReps,
      aliases: ['硬舉', 'Deadlift', 'DL'],
      level1: '重訓',
      level2: '背',
      bodyParts: ['背', '腿'],
      bodyPart: '背',
    ),

    // ex-005: 引體向上（vertical_pull, pull, bodyweight, advanced）
    make(
      id: 'ex-005',
      name: '引體向上',
      nameEn: 'Pull Up',
      canonicalName: '徒手引體向上',
      canonicalNameEn: 'Bodyweight Pull Up',
      movementPatterns: ['vertical_pull'],
      pplTags: ['pull'],
      primaryMuscle: 'lats',
      synergistMuscles: ['biceps', 'rear_deltoid'],
      equipment: 'bodyweight',
      mechanicsType: 'compound',
      difficultyLevel: 'advanced',
      isExplosive: false,
      trackingMode: TrackingMode.repsOnly,
      aliases: ['拉單槓', 'Chin Up'],
      level1: '重訓',
      level2: '背',
      bodyParts: ['背'],
      bodyPart: '背',
    ),

    // ex-006: 瞬發上搏（hinge, legs, barbell, advanced, explosive）
    make(
      id: 'ex-006',
      name: '瞬發上搏',
      nameEn: 'Power Clean',
      canonicalName: '槓鈴瞬發上搏',
      canonicalNameEn: 'Barbell Power Clean',
      movementPatterns: ['hinge'],
      pplTags: ['legs'],
      primaryMuscle: 'quads',
      synergistMuscles: ['glutes', 'hamstrings', 'traps'],
      equipment: 'barbell',
      mechanicsType: 'compound',
      difficultyLevel: 'advanced',
      isExplosive: true,
      trackingMode: TrackingMode.weightReps,
      aliases: ['爆發上搏', 'Clean'],
      level1: '重訓',
      level2: '全身',
      bodyParts: ['全身'],
      bodyPart: '全身',
    ),

    // ex-007: 棒式（anti_extension, core, bodyweight, beginner）
    make(
      id: 'ex-007',
      name: '棒式',
      nameEn: 'Plank',
      canonicalName: '徒手棒式',
      canonicalNameEn: 'Bodyweight Plank',
      movementPatterns: ['anti_extension'],
      pplTags: ['core'],
      primaryMuscle: 'abs',
      synergistMuscles: ['obliques'],
      equipment: 'bodyweight',
      mechanicsType: 'compound',
      difficultyLevel: 'beginner',
      isExplosive: false,
      trackingMode: TrackingMode.timeOnly,
      aliases: ['平板支撐', 'Front Plank'],
      level1: '核心',
      level2: '腹',
      bodyParts: ['核心'],
      bodyPart: '核心',
    ),

    // ex-008: 前弓箭步（lunge, legs, bodyweight, beginner）
    make(
      id: 'ex-008',
      name: '前弓箭步',
      nameEn: 'Forward Lunge',
      canonicalName: '徒手前弓箭步',
      canonicalNameEn: 'Bodyweight Forward Lunge',
      movementPatterns: ['lunge'],
      pplTags: ['legs'],
      primaryMuscle: 'quads',
      synergistMuscles: ['glutes', 'hamstrings'],
      equipment: 'bodyweight',
      mechanicsType: 'compound',
      difficultyLevel: 'beginner',
      isExplosive: false,
      isUnilateral: true,
      trackingMode: TrackingMode.repsOnly,
      aliases: ['前跨步蹲', 'Walking Lunge'],
      level1: '重訓',
      level2: '腿',
      bodyParts: ['腿'],
      bodyPart: '腿',
    ),

    // ex-009: 纜繩三頭下壓（isolation_push, push, cable, beginner, isolation）
    make(
      id: 'ex-009',
      name: '纜繩三頭下壓',
      nameEn: 'Cable Tricep Pushdown',
      canonicalName: '纜繩三頭下壓',
      canonicalNameEn: 'Cable Tricep Pushdown',
      movementPatterns: ['isolation_push'],
      pplTags: ['push'],
      primaryMuscle: 'triceps',
      synergistMuscles: [],
      equipment: 'cable',
      mechanicsType: 'isolation',
      difficultyLevel: 'beginner',
      isExplosive: false,
      trackingMode: TrackingMode.weightReps,
      aliases: ['三頭下壓', 'Pushdown'],
      level1: '重訓',
      level2: '手臂',
      bodyParts: ['手臂'],
      bodyPart: '手臂',
    ),

    // ex-010: 坐姿划船（horizontal_pull, pull, cable, intermediate）
    make(
      id: 'ex-010',
      name: '坐姿划船',
      nameEn: 'Seated Cable Row',
      canonicalName: '坐姿纜繩划船',
      canonicalNameEn: 'Seated Cable Row',
      movementPatterns: ['horizontal_pull'],
      pplTags: ['pull'],
      primaryMuscle: 'lats',
      synergistMuscles: ['biceps', 'rear_deltoid', 'traps'],
      equipment: 'cable',
      mechanicsType: 'compound',
      difficultyLevel: 'intermediate',
      isExplosive: false,
      trackingMode: TrackingMode.weightReps,
      aliases: ['Cable Row', '纜繩划船'],
      level1: '重訓',
      level2: '背',
      bodyParts: ['背'],
      bodyPart: '背',
    ),

    // ex-011: 壺鈴擺盪（hinge, legs+cardio, kettlebell, intermediate, explosive）
    make(
      id: 'ex-011',
      name: '壺鈴擺盪',
      nameEn: 'Kettlebell Swing',
      canonicalName: '壺鈴擺盪',
      canonicalNameEn: 'Kettlebell Swing',
      movementPatterns: ['hinge'],
      pplTags: ['legs', 'cardio'],
      primaryMuscle: 'glutes',
      synergistMuscles: ['hamstrings', 'erector_spinae'],
      equipment: 'kettlebell',
      mechanicsType: 'compound',
      difficultyLevel: 'intermediate',
      isExplosive: true,
      trackingMode: TrackingMode.weightReps,
      aliases: ['KB Swing', '壺鈴甩'],
      level1: '功能性',
      level2: '全身',
      bodyParts: ['全身'],
      bodyPart: '全身',
    ),

    // ex-012: 股四頭伸展（mobility, mobility, bodyweight, beginner, isolation）
    make(
      id: 'ex-012',
      name: '股四頭伸展',
      nameEn: 'Quad Stretch',
      canonicalName: '股四頭伸展',
      canonicalNameEn: 'Quad Stretch',
      movementPatterns: ['mobility'],
      pplTags: ['mobility'],
      primaryMuscle: 'quads',
      synergistMuscles: [],
      equipment: 'bodyweight',
      mechanicsType: 'isolation',
      difficultyLevel: 'beginner',
      isExplosive: false,
      trackingMode: TrackingMode.repsTime,
      aliases: ['大腿前側伸展'],
      level1: '伸展',
      level2: '腿',
      bodyParts: ['腿'],
      bodyPart: '腿',
    ),
  ];
}
